# Name of your quickstart as shown on the website
name: Varnish
description: |+
  Describe what's the focus of your dashboards.
  You can use multiple lines.
  Try to be as descriptive as possible.

# Optional: Authors of the quickstart
authors:
    - New Relic
    - Jakub Kotkowiak

